title: Analysis of Top 100 Songs of All Time
description: STA 141B Final Project
sitename: STA 141B Final Project
baseurl: 'https://jiahtan.github.io/STA141B/'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
